lib/sprout_tree_web/router.ex
defmodule SproutTreeWeb.Router do
  use SproutTreeWeb, :router

  defp maybe_add_user(conn, _) do
    maybe_user = Guardian.Plug.current_resource(conn)
    assign(conn, :maybe_user, maybe_user)
  end

  pipeline :auth do
    plug(SproutTree.Accounts.Auth.Pipeline)
    plug(:maybe_add_user)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :ensure_admin do
    plug(SproutTreeWeb.Auth.CheckAdmin)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", SproutTreeWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)

    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)
    resources("/users", UserController, only: [:new, :create])
  end

  scope "/admin", SproutTreeWeb.Admin, as: :admin do
    pipe_through([:browser, :auth, :ensure_auth, :ensure_admin])

    get("/", PageController, :index)
    resources("/plant_types", PlantTypeController)
  end

  scope "/pms", SproutTreeWeb.PMS, as: :pms do
    pipe_through([:browser, :auth, :ensure_auth])

    resources("/users", UserController, only: [:show, :edit, :update, :delete])

    resources(
      "/sprout_requests",
      SproutRequestController,
      only: [:index, :update, :delete]
    )

    resources("/invitations", SproutInvitationController, only: [:delete])
    get("/invitations/:verification_code", SproutInvitationController, :show)
    post("/invitations/:id/accept", SproutInvitationController, :accept)

    post(
      "/invitations/:id/accept_to_existing_sprout",
      SproutInvitationController,
      :accept_to_existing_sprout
    )

    resources "/sprouts", SproutController do
      get("/invitations/generate", SproutInvitationController, :generate)
      get("/invitations/generate_parent", SproutInvitationController, :generate_parent)

      resources("/requests", SproutRequestController, only: [:new, :create])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SproutTreeWeb do
  #   pipe_through :api
  # end
end

lib/sprout_tree_web/views/layout_view.ex
defmodule SproutTreeWeb.LayoutView do
  use SproutTreeWeb, :view
end

lib/sprout_tree_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sticklingsträdet</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
          <a class="navbar-brand" href="/">Sticklingsträdet</a>
          <%= if @maybe_user == nil do %>
            <%= link "Logga in", class: "nav-item", to: session_path(@conn, :new) %>
            <%= link "Skapa konto", class: "nav-item", to: user_path(@conn, :new) %>
          <% else %>
            <span class="nav-item"><%= @maybe_user.credential.email %></span>
            <%= link "Mina växter", class: "nav-item", to: pms_sprout_path(@conn, :index) %>
            <%= link "Logga ut", class: "nav-item", to: session_path(@conn, :delete), method: "delete", as: :user %></li>
          <% end %>
        </nav>
      </header>

      <%= unless is_nil(get_flash(@conn, :info)) do %>
        <p class="alert alert-success" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= unless is_nil(get_flash(@conn, :error)) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>